package busqueda.lineal;


import java.util.Arrays;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class FrmBusqueda extends javax.swing.JFrame {
 int vec[]=new int[100];
    int iteracion=0;
    int elemento=0;
    int salir=0;
    int lista;
   
   DefaultListModel modelo = new DefaultListModel();
    public FrmBusqueda() {
        initComponents();
    }
    
   public static int busquedaBinaria(int  vector[], int dato){
  int n = vector.length;
  int centro = 0,inf=0,sup=n-1;
   while(inf<=sup){
     centro=(sup+inf)/2;
     if(vector[centro]==dato)
     {
         inf=1000;
     }
         
     else if(dato < vector [centro] ){
        sup=centro-1;
     }
     else {
       inf=centro+1;
     }
   }
   
   return centro;
 }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnBusquedalineal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltsnum = new javax.swing.JList<>();
        txtbusq = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        btnBusquedaBinaria = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        btnInserccion = new javax.swing.JButton();
        btnCombinacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBusquedalineal.setText("Busqueda Lineal");
        btnBusquedalineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedalinealActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ltsnum);

        btnBusquedaBinaria.setText("Busqueda Binaria");
        btnBusquedaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaBinariaActionPerformed(evt);
            }
        });

        btnSeleccion.setText("Ordenamiento por Seleccion");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        btnInserccion.setText("Ordenamiento por Inserccion");
        btnInserccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserccionActionPerformed(evt);
            }
        });

        btnCombinacion.setText("Ordenamiento por Combinacion");
        btnCombinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtbusq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCombinacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInserccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBusquedaBinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBusquedalineal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addGap(31, 31, 31)
                        .addComponent(btnBusquedalineal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusquedaBinaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInserccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCombinacion)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     
      modelo.addElement(txtnumero.getText());
      ltsnum.setModel(modelo);
      txtnumero.setText("");
      

    
        
       
         
      
      elemento++;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBusquedalinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedalinealActionPerformed
      salir=0;
      iteracion=0;
        while( iteracion<elemento && salir==0)
       {
           ltsnum.setSelectedIndex(iteracion);
           if(ltsnum.getSelectedValue().toString().equals(txtbusq.getText()))
           {
               
               JOptionPane.showMessageDialog(null, iteracion);
               salir=1;
           }
           iteracion++;
       }
    }//GEN-LAST:event_btnBusquedalinealActionPerformed

    private void btnBusquedaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaBinariaActionPerformed
  
         for ( lista=0;lista<elemento;lista++)
        {
            ltsnum.setSelectedIndex(iteracion);
            vec[lista]=Integer.parseInt(ltsnum.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
    
       int seleccion, comparar, menor, pos, aux;
         for (seleccion=0;seleccion<elemento-1;seleccion++) 
          { 
            menor = vec[seleccion]; 
            pos = seleccion; 
            for (comparar=seleccion+1;comparar<elemento;comparar++)
                { 
                if (vec[comparar]<menor) 
                   { 
                    menor=vec[comparar]; 
                    pos=comparar;
                   }
                }
                if (pos!=seleccion)
                { 
                    aux = vec[seleccion];
                    vec[seleccion]=vec[pos];
                    vec[pos]=aux;
                    
                }
               
          }
        
  
  int valorBuscado = Integer.parseInt(txtbusq.getText());

  int largo = elemento;
  int centro=0,inf=0,sup=largo-1;
   while(inf<=sup){
     centro=(sup+inf)/2;
     if(vec[centro]==valorBuscado)
     {
         iteracion++;
         inf=1000;
     }
         
     else if(valorBuscado < vec [centro] ){
        sup=centro-1;
        iteracion++;
     }
     else {
       inf=centro+1;
       iteracion++;
     }
   }
   
   
   String vec1[]=new String[100];
 
 
modelo.addElement("La lista ordenada es");
      ltsnum.setModel(modelo);
 
 
 
          for( lista=0;lista<elemento;lista++)
          {
              
            vec1[lista]=String.valueOf(vec[lista]);  
             modelo.addElement(vec[lista]);
      ltsnum.setModel(modelo);

          }
          
          JOptionPane.showMessageDialog(null,"El valor esta en la posicion "+centro+" realizando "+iteracion+" iteraciones");
 
      System.out.print(centro);
      
  
  

        
        
        
        
  
    }//GEN-LAST:event_btnBusquedaBinariaActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
       int seleccion, comparar, menor, pos, aux;
          for ( lista=0;lista<elemento;lista++)
        {
            ltsnum.setSelectedIndex(iteracion);
            vec[lista]=Integer.parseInt(ltsnum.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
        
      
        
       
          for (seleccion=0;seleccion<elemento-1;seleccion++) 
          { 
            menor = vec[seleccion]; 
            pos = seleccion; 
            for (comparar=seleccion+1;comparar<elemento;comparar++)
                { 
                if (vec[comparar]<menor) 
                   { 
                    menor=vec[comparar]; 
                    pos=comparar;
                   }
                }
                if (pos!=seleccion)
                { 
                    aux = vec[seleccion];
                    vec[seleccion]=vec[pos];
                    vec[pos]=aux;
                    iteracion++;
                }
               
          }
          
          
          
          
 String vec1[]=new String[100];
 
 
modelo.addElement("La lista ordenada es");
      ltsnum.setModel(modelo);
 
 
 
          for( lista=0;lista<elemento;lista++)
          {
              
            vec1[lista]=String.valueOf(vec[lista]);  
             modelo.addElement(vec[lista]);
      ltsnum.setModel(modelo);

          }
          
          JOptionPane.showMessageDialog(null, iteracion);
          
       
        
    
   
        
        
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void btnInserccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserccionActionPerformed
       for ( lista=0;lista<elemento;lista++)
        {
            ltsnum.setSelectedIndex(iteracion);
            vec[lista]=Integer.parseInt(ltsnum.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
       
    int inserccion, anterior,aux;
   
    for (inserccion = 1; inserccion < elemento; inserccion++)
    { 
        aux = vec[inserccion]; 
        anterior = inserccion - 1;
        while ((anterior >= 0) && (aux < vec[anterior]))
        { 
            vec[anterior + 1] = vec[anterior];       
            anterior--;  
            iteracion++;
        }
        vec[anterior + 1] = aux; 
    }
         String vec1[]=new String[100];
 
 
modelo.addElement("La lista ordenada es");
      ltsnum.setModel(modelo);
 
 
 
          for( lista=0;lista<elemento;lista++)
          {
              
            vec1[lista]=String.valueOf(vec[lista]);  
             modelo.addElement(vec[lista]);
      ltsnum.setModel(modelo);

          }
    
        
        JOptionPane.showMessageDialog(null, iteracion);
        
    }//GEN-LAST:event_btnInserccionActionPerformed

    private void btnCombinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinacionActionPerformed
       for ( lista=0;lista<elemento;lista++)
        {
            ltsnum.setSelectedIndex(iteracion);
            vec[lista]=Integer.parseInt(ltsnum.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
        
        
          
    }//GEN-LAST:event_btnCombinacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBusquedaBinaria;
    private javax.swing.JButton btnBusquedalineal;
    private javax.swing.JButton btnCombinacion;
    private javax.swing.JButton btnInserccion;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ltsnum;
    private javax.swing.JTextField txtbusq;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
